version: "3.8"

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "movie_crawler_db"
    ports:
      - "5432:5432"
